### ISSUE TITLE
Lack of 'emo' package and How to install it

### ISSUE THREAD

**Issue by NickDuley** [STA518-Spring20/discussion#55] opened 2020-05-27 22:30 UTC
I had an issue with the 'emo' package not being present for the activity due tonight, and while I was able to find the solution, having the resources here would be easier than finding it every time i's needed.

1. Install the devtools package ( install.packages('devtools'))
2. Copy and paste the following code into the console: devtools::install_github("hadley/emo")
3. Congrats. You now can use emotes

**Comment by shroom552** [comment] 2020-05-27 22:55
Where should we install the devtools package? We aren't suppose to use install in our .rmd due to code etiquette.

**Comment by NickDuley** [comment] 2020-05-27 22:58
Just install it into the console like if you were to install tidyverse manually (e.g install.packges("tidyverse"))

**Comment by dykesb** [comment] 2020-05-28 11:57
Duplicate of #8

**Closed as completed by dykesb** 2020-05-28 11:57 UTC
