### ISSUE TITLE
Error in loadNamespace(name)

### ISSUE THREAD

**Issue by shroom552** [STA518-Spring20/discussion#56] opened 2020-05-27 22:32 UTC
I'm having issues with knitting my Activity0203. At first it provided me with a list of packages I needed to install. I assumed that at some point they had gotten cleared out and reloaded the ones that were suggested. However, now I'm receiving a new error message shown below I didn't want to go much further with trying to solve the problem myself as I feel over my head. In the mean time I'll continue with the assignment and will  only be saving my changes instead of knitting.

Attachments area
![Activity0203 error](https://user-images.githubusercontent.com/36728300/83078788-5c9b6a00-a048-11ea-974c-d7baead5c8ee.JPG)

**Comment by dykesb** [comment] 2020-05-27 22:46
Answered in #55

**Comment by dykesb** [comment] 2020-05-28 11:58
Duplicate of #8

**Closed as completed by dykesb** 2020-05-28 11:58 UTC
